package.json, src/index.js
This addresses most of #3. I think for the `Protocols` variable, this should be left to the implementer to decide if the router should explicitly support particular protocols or check if a peer is using a particular protocol.
=> Added a time cache and a topic mapping. 

.travis.yml, README.md, ci/Jenkinsfile, package.json
After the discussion in [libp2p/js-libp2p-floodsub#69](https://github.com/libp2p/js-libp2p-floodsub/pull/69), the docs were improved regarding the functions to overwrite.
The CI was also switched to travis in this PR
=> docs: overwritten functions

src/index.js
The utils codebase is useful both for `floodsub` and `gossipsub` implementations. 
[libp2p/js-libp2p-floodsub#76](https://github.com/libp2p/js-libp2p-floodsub/pull/76/files) browser CI is currently failing, as a result of requiring the file through its path.
=> chore: export pubsub utils

src/index.js, src/message/index.js, src/message/rpc.proto.js, src/message/sign.js, src/peer.js, src/utils.js, test/pubsub.js, test/sign.spec.js
BREAKING CHANGE: as .publish should now sign messages (via _buildMessage) it now requires a callback since signing is async. This also adds an options param to the pubsub constructor to allow for disabling signing. While this change shouldnt break things upstream, implementations need to be sure to call _buildMessage for each message they will publish.
Adds signing support (on by default) for https://github.com/libp2p/js-libp2p-pubsub/issues/16.
=> feat: add support for message signing

README.md, package.json, src/index.js, src/message/sign.js, src/utils.js, test/pubsub.spec.js, test/sign.spec.js
This adds an option to pubsub, `strictSigning` which defaults to `true`. When `validate` is called, the signature of the message will be verified, unless `strictSigning` is disabled.
I originally intended to enforce this at the pubsub interface layer so that both Floodsub and Gossipsub could get the behavior out of the box, however, the implementations don't use the same message processing pipeline. Ideally, we should unify this more so that the abstraction layer can do common validation, like signature validation, before moving on to implementation specific message processing.
As it stands, `validate` is going to need to be called in both implementations in their respective pipelines. I will be creating PRs for both implementations.
=> feat: verify signatures

.travis.yml, package.json, src/message/sign.js, test/sign.spec.js
This has unlocked the ability for supporting pubsub messages with Secp256k1 keys: https://github.com/libp2p/js-peer-id/pull/102
This is a pretty straight forward PR, if the message.key does not exist, it attempts to get the public key from the message from and if that doesn't exist, errors as it did previously.
=> allow inline public keys in messages

src/index.js, test/pubsub.spec.js
`libp2p.handle` sends conn and not `remotePeer`
=> fix: incoming stream conn

src/index.js, test/pubsub.spec.js
BREAKING CHANGE: getPeersSubscribed renamed to getSubscribers to remove redundant wording
Per discussion on `js-libp2p` new API PR: https://github.com/libp2p/js-libp2p/pull/472/files#r352186893
=> chore: getSubscribers

README.md
When we renamed the `getPeersSubscribed` to `getSubscribers`, I missed this in the Readme.
=> chore: fix getSubscribers api doc

src/index.js, test/pubsub.spec.js
* Connection.newStream can throw errors and they weren't being caught. This now catches and logs those errors.
* If a disconnection occurred for a peer we are not tracking, removePeer would be called with undefined which would throw an error. This fixes that by checking for its existence before attempting to remove it.
=> fix: catch newStream errors

src/index.js
This is a correction that was discovered in https://github.com/ChainSafe/gossipsub-js/pull/58.
=> docs(fix): correct jsdocs for _processMessages

README.md, package.json, src/index.js, src/peer.js, test/instance.spec.js, test/pubsub.spec.js, test/utils/index.js
In the context of deprecating `peer-info` as described on [libp2p/js-libp2p#589](https://github.com/libp2p/js-libp2p/issues/589), this PR removes the `peer-info` usage on pubsub internal peer data structure. Moreover, this uses the new topology API, which also uses `peer-id` instead of `peer-info`
This changes have impact on pubsub implementations.
BREAKING CHANGE: pubsub internal peer does not have info propery anymore and use the new topology api with peer-id instead of peer-info
Needs:
=> chore: remove peer-info usage

README.md
Gossipsub repo url changed from `ChainSafe/gossipsub-js` to `ChainSafe/js-libp2p-gossipsub`
=> chore: change libp2p-gossipsub url

src/index.js, src/peer.js
This PR makes libp2p pubsub subsystem use unidirectional streams instead of bidirectional streams per discussion on [ipfs/go-ipfs#7390](https://github.com/ipfs/go-ipfs/issues/7390).
It replicates #45 for the `0.4.x` version range of `libp2p-pubsub`
More details about the reasoning for this can be found in https://discuss.libp2p.io/t/gossip-questions/257/6
=> fix: use unidirectional streams for v0.4.x

src/index.js, src/peer.js
This PR makes libp2p pubsub subsystem use unidirectional streams instead of bidirectional streams per discussion on [ipfs/go-ipfs#7390](https://github.com/ipfs/go-ipfs/issues/7390).
More details about the reasoning for this can be found in https://discuss.libp2p.io/t/gossip-questions/257/6
=> fix: use unidirectional streams

src/index.js, test/pubsub.spec.js
Added a validation before creating a new stream per [libp2p/js-libp2p#668#issuecomment-643375326](https://github.com/libp2p/js-libp2p/issues/668#issuecomment-643375326).
=> fix: not create stream if it already exists

src/index.js, src/peer.js, test/pubsub.spec.js
This ensures pubsub always uses the newest connection, which fixes problems like https://github.com/libp2p/js-libp2p/pull/693.
This also includes the ref removal from https://github.com/libp2p/js-libp2p-pubsub/pull/55 for the 0.5 line.
=> fix: quick reconnects

src/index.js, src/peer.js, test/pubsub.spec.js
Now that we use unidirectional streams, we do not need to track references. This was causing us to increase them and not removing the peer.
This also got a fix for quick reconnects from https://github.com/libp2p/js-libp2p-pubsub/pull/57 to `0.4.x`
=> fix: remove references

src/index.js, src/message/sign.js, src/utils.js, test/utils.spec.js
Addresses https://github.com/libp2p/js-libp2p-pubsub/issues/50
Additionally includes a `receivedFrom` entry on a normalized InMessage. This will aid downstream routers by creating a fully self-contained object that doesn't need to have the receivedFrom peerId passed as a separate parameter. This idea was taken from go-libp2p-pubsub.
This PR is backwards compatible, future PRs will likely break compatibility at some point.
=> chore: refactor message normalization

src/index.js
Resolves https://github.com/libp2p/js-libp2p-pubsub/issues/51
BREAKING CHANGE: the publish function signature now takes a single
message as its second parameter, instead of optionally an array of
messages.
=> feat: update publish function signature

src/index.js, test/pubsub.spec.js
- change `topics` to map `topic` to `Set<peerIdStr>`
- clean up peer topics in `_removePeer`
=> chore: refactor topics map

src/message/sign.js
Code reorganization of `messagePublicKey`
Previously, a non-buffer `message.from` would cause an error in `peerId.isEqual(message.from)`.
https://github.com/libp2p/js-peer-id/blob/master/src/index.js#L154
=> chore: refactor messagePublicKey

src/index.js, src/message/sign.js
Fix verifySignature function to take an `InMessage` object (in a 'backwards compatible' way)
Fix verifySignature usage (was not awaiting the result!)
=> chore: fix verifySignature

package.json, src/message/sign.js, src/peer.js, src/utils.js, test/sign.spec.js, test/utils.spec.js
All uses of node Buffers have been replaced with Uint8Arrays
BREAKING CHANGES:
- The `.data` and `.seq` properties of messages used to be node Buffers, now they are Uint8Arrays
- All deps of this module now use Uint8Arrays instead of Buffers
=> fix: replace node buffers with uint8arrays

package.json, src/index.ts, test/utils/index.ts
BREAKING CHANGE: update to simpler connection api
=> chore!: update deps

package.json, src/index.ts
Pass `maxInboundStreams` and `maxOutboundStreams` options to registrar
=> fix: limit stream concurrency

src/index.ts, test/pubsub.spec.ts
Now that we route all messages via a `'message'` event, we can't check
the number of listeners for a given topic using the listener count.
=> fix: do not unsubscribe after publish

package.json, src/index.ts, src/peer-streams.ts, src/sign.ts, src/utils.ts, test/instance.spec.ts, test/lifecycle.spec.ts, test/message.spec.ts, test/message/rpc.ts, test/pubsub.spec.ts, test/sign.spec.ts, test/utils.spec.ts, test/utils/index.ts
Update deps to support no-copy operations
=> deps: update it-length-prefixed and uint8arraylists deps

package.json, src/index.ts, test/emit-self.spec.ts, test/instance.spec.ts, test/lifecycle.spec.ts, test/message.spec.ts, test/message/rpc.ts, test/pubsub.spec.ts, test/topic-validators.spec.ts
`@libp2p/components` is a choke-point for our dependency graph as it depends on every interface, meaning when one interface revs a major `@libp2p/components` major has to change too which means every module depending on it also needs a major.
Switch instead to constructor injection of simple objects that let modules declare their dependencies on interfaces directly instead of indirectly via `@libp2p/components`
Refs https://github.com/libp2p/js-libp2p-components/issues/6
BREAKING CHANGE: modules no longer implement `Initializable` instead switching to constructor injection
=> fix!: remove @libp2p/components

src/utils.ts, test/utils.spec.ts
Allows field key to not be set in case key can be extracted from the sender's peer ID. (as per https://github.com/libp2p/specs/tree/master/pubsub#message-signing)
=> fix: allow `key` field to be unset

src/utils.ts, test/utils.spec.ts
Remove the `@ts-expect-error` and use the public key of the peer id if it's not specified in the message.
=> fix: get key from peer id if not specified in the message
